<?php

/**
 * @file
 * Main module file for PW Datatransfers module for hooks
 */


/**
 * Implements hook_menu().
 */
function pw_datatransfers_menu() {
  // Path for old Modtool way to import dialogues
  $items['api/import/dialogue/%'] = [
    'title' => 'imports dialogue',
    'access arguments' => array('access content'),
    'page callback' => 'pw_datatransfers_dialogue_import_old',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'file' => 'pw_datatransfers.pagecallbacks.inc'
  ];

  // Path for new Modtool way to import dialogues
  $items['api/dialogues'] = [
    'page callback' => 'pw_datatransfers_dialogue_import',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'pw_datatransfers.pagecallbacks.inc'
  ];

  return $items;
}


/**
 * Implements hook_entity_info().
 */
function pw_datatransfers_entity_info() {
  $custom_entities = [];

  // the dialogue import log entry entity
  $custom_entities['dialogue_import_log'] = [
    'label' => t('Dialogue Import log entry'),
    'base table' => 'pw_datatransfers_logs_dialogue',
    'entity keys' => [
      'id' => 'id'
    ],
    'entity class' => '\Drupal\pw_datatransfers\Entity\LogDialogueImportEntity',
    'controller class' => '\Drupal\pw_datatransfers\Entity\LogDialogueImportController',
    'module' => 'pw_datatransfers'
  ];

  return $custom_entities;
}


/**
 * Implements hook_permission().
 */
function pw_datatransfers_permission() {
  return [
    'see datatransfer logs' => [
      'title' => 'See datatransfer logs',
      'description' => 'Can see the log entries'
    ]
  ];
}