<?php

/**
 * @file
 * Module file for PW Imports modules for Drupal hooks
 */


/**
 * Implements hook_menu().
 */
function pw_imports_menu() {
  $items = [];

  $items['admin/abgeordnetenwatch/imports/add'] = [
    'title' => 'Add new import',
    'page callback' => 'pw_imports_addform_pagecallback',
    'access arguments' => ['administrate an import'],
    'type' => MENU_CALLBACK,
    'file' => 'pw_imports.pagecallbacks.inc'
  ];

  $items['admin/abgeordnetenwatch/imports/%pw_import/edit'] = [
    'title' => 'Edit import',
    'page callback' => 'pw_imports_editorm_pagecallback',
    'page arguments' => [3],
    'access arguments' => ['administrate an import'],
    'type' => MENU_CALLBACK,
    'file' => 'pw_imports.pagecallbacks.inc'
  ];


  $items['admin/abgeordnetenwatch/imports/%pw_import'] = [
    'title' => 'Administrate import',
    'page callback' => 'pw_imports_view_pagecallback',
    'page arguments' => [3],
    'access arguments' => ['administrate an import'],
    'type' => MENU_CALLBACK,
    'file' => 'pw_imports.pagecallbacks.inc'
  ];


  return $items;
}


/**
 * Loader function for Imports
 *
 * @param int|string $id
 * The id of the import
 *
 * @return \Drupal\pw_imports\Import\Import
 */
function pw_import_load($id) {
  return \Drupal\pw_imports\Import\Import::load($id);
}


/**
 * Implements hook_permission().
 */
function pw_imports_permission() {
  return [
    'administrate an import' => [
      'title' => t('Administrate an import'),
      'description' => t('Needed to create, edit and finish imports')
    ]
  ];
}

