<?php

/**
 * @file pw_cron_export_submissions.module
 * cron to write submissions to a json file which will be regularly imported by an external civicrm cron
 */


/**
 * Implements hook_cron()..
 */
function pw_cron_export_submissions_cron() {

  // export submissions of webform spendenformular
  pw_cron_export_export_submissions(10508);
  pw_cron_export_delete_submissions(10508, 3);


  // export submissions of webform petition-unterschreiben
  pw_cron_export_export_submissions(10369);
  pw_cron_export_delete_submissions(10369, 3);

  // export submissions of webform newsletter-subscription
  pw_cron_export_export_submissions(10380);
  pw_cron_export_delete_submissions(10380, 16, 3);

  // export submissions of webform kontakt
  pw_cron_export_delete_submissions(6578, 0);

  // export submissions of webform aufkleber-bestellen
  pw_cron_export_export_submissions(65995);
  pw_cron_export_delete_submissions(65995, 0);

  // export submissions of webform spenden-sie-einmalig-oder-fordern-sie-regelmassig
  pw_cron_export_delete_submissions(104846, 0);

  // export submissions of webform foerderung-verschenken
  pw_cron_export_delete_submissions(108699, 30);

  // export submissions of webform als-kandidatin-oder-kandidat-auf-abgeordnetenwatchde-eintragen
  pw_cron_export_delete_submissions(176108, 0);

  // export submissions of webform transparenztasse
  pw_cron_export_delete_submissions(681042, 30);

  // export submissions of webform newsletter-abmeldung
  pw_cron_export_export_submissions(111893);
  pw_cron_export_delete_submissions(111893, 7);

  // export submissions of webform frage-stellen
  pw_cron_export_export_submissions(10446);
  pw_cron_export_delete_submissions(10446, 7);

}


/**
 *  Exports submissions of a webform to files/private
 *
 * @param int $nid
 *   The webform nid.
 *
 */

function pw_cron_export_export_submissions($nid){

  if($webform = node_load($nid)){

    // load webform module
    module_load_include('inc', 'webform', 'includes/webform.submissions');

    // query db for subscribed & confirmed submissions
    $submissions_confirmed = db_query("SELECT wf_data.sid FROM webform_submitted_data wf_data LEFT OUTER JOIN webform_confirm_email_code wf_email_code ON wf_data.sid = wf_email_code.sid WHERE wf_data.nid = :nid AND wf_data.data = 'subscribed' AND wf_email_code.code IS NULL", array(':nid' => $webform->nid))
      ->fetchCol();

    if(sizeof($submissions_confirmed) > 0){

      // query db to retrieve webform components
      $form_fields = db_query("SELECT wf_comp.cid, wf_comp.form_key FROM webform_component wf_comp WHERE wf_comp.nid = :nid", array(':nid' => $webform->nid))
        ->fetchAllAssoc('cid');

      // load submissions
      $submissions = webform_get_submissions(array('sid' => $submissions_confirmed));

      // prepare
      $cid_status_field = false;
      $cid_node_path_field = false;
      foreach($form_fields as $cid => $component){
        if($component->form_key == 'status'){
          $cid_status_field = $cid;
        }
        elseif($component->form_key == 'node_path'){
          $cid_node_path_field = $cid;
        }
      }

      // prepare export path
      $export_path = "private://webforms/submissions/";
      $export_path .= str_replace('/', '_', $source).'/';
      if(!file_prepare_directory($export_path, FILE_CREATE_DIRECTORY)){
        watchdog('pw_cron_export_submissions_cron', 'could not create export path: '.$export_path, NULL, WATCHDOG_WARNING);
        return;
      }

        // @TODO: Check $cid_status_field and $export_path

      // write submissions to json file
      foreach($submissions as $submission){
        $submission->data[$cid_status_field][0] = 'exported';
        $url_alias = drupal_get_path_alias($submission->data[$cid_node_path_field][0]);
        $submission->export_url_alias = $url_alias;
        foreach($form_fields as $cid => $component){
          $form_key = 'export_'.$component->form_key;
          $submission->$form_key = $submission->data[$cid][0];
        }
      }

      // export to json
      $file_json_content = json_encode($submissions);
      $file_json_path = $export_path.'submissions_'.time().'.json';
      $file_json = file_save_data($file_json_content, $file_json_path, FILE_EXISTS_RENAME);

      // on success update submissions to status=exported
      if($file_json){
        foreach($submissions as $submission){
          webform_submission_update($webform, $submission);
        }
      }
    }

  }
}

/**
 *  Deletes submissions of a webform
 *
 * @param int $nid
 *   The webform nid.
 *
 * @param int $delete_general
 *   Days after submissions should be deleted in general.
 *
 * @param int $delete_exported
 *   Days after exported submissions should be deleted.
 *
 */

function pw_cron_export_delete_submissions($nid, $delete_general, $delete_exported=FALSE) {

  if ($webform = node_load($nid)) {

    if (!$delete_exported) {
      $delete_exported = $delete_general;
    }

    $timestamp_exported = time() - $delete_exported * 86400;
    $timestamp_general = time() - $delete_general * 86400;

    // query db for submissions to be deleted
    $submissions_to_delete = db_query("SELECT wf_data.sid FROM webform_submitted_data wf_data LEFT OUTER JOIN webform_submissions wf ON wf_data.sid = wf.sid WHERE wf_data.nid = :nid AND (wf_data.data = 'exported' AND wf.submitted < ".$timestamp_exported." OR wf.submitted < ".$timestamp_general.")", array(':nid' => $webform->nid));


    $q = db_select("webform_submitted_data", "wf_data");
    $q->addField("wf_data", "sid");
    $q->leftJoin('webform_submissions', 'wf', 'wf_data.sid = wf.sid');
    $q->condition('wf_data.nid', $nid);
    $db_and = db_and()
      ->condition("wf_data.data", "exported")
      ->condition("wf.submitted", $timestamp_exported, "<");
    $db_or = db_or()
      ->condition('wf.submitted', $timestamp_general, "<")
      ->condition($db_and);
    $q->condition($db_or);

    print $q->execute()->rowCount();
    print " <- ";
    print $submissions_to_delete->rowCount();
    print "\n";
    return TRUE;

    // (wf_data.data = 'exported'
    // AND wf.submitted < ".$timestamp_exported."
    // OR wf.submitted < ".$timestamp_general.")

    if(sizeof($submissions_to_delete) > 0){

      // load submissions
      $submissions = webform_get_submissions(array('sid' => $submissions_to_delete));

      // delete submissions
      foreach($submissions as $submission){
        webform_submission_delete($webform, $submission);
      }
    }
  }
}