<?php

/**
 * @file
 * Update functions for the pw_blog module.
 */

/**
 * Implements hook_uninstall().
 */
function pw_blog_uninstall() {

}


/**
 * Enable and configure spamicide for spam protection.
 */
function pw_blog_update_7100() {
  module_enable(['spamicide'], FALSE);
  db_query("UPDATE spamicide SET form_field='please_update_me', enabled=1 WHERE form_id='comment_node_blogpost_form'");
}