<?php


use Drupal\pw_globals\Parliament;
use Drupal\pw_globals\Politician;
use Drupal\pw_globals\PoliticianUserRevision;
use Drupal\pw_globals\PWUser;
use Drupal\pw_userarchives\UserArchiveDatabase;
use Drupal\pw_userarchives\UserArchiveEntry;
use Drupal\pw_userarchives\UserArchiveManager;


/**
 * Implements hook_menu().
 */
function pw_userarchives_menu() {

  // Creates menu hook for editing user revisions.
  $items['user/%user_revision/revisions/%/edit'] = array(
    'title' => 'Edit this revision',
    'load arguments' => array(3),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pw_userarchives_user_revision_edit_form', 1),
    'access callback' => 'pw_userarchives_user_revision_admin_access',
    'access arguments' => array(1),
    'file' => 'pw_userarchives.admin.inc',
  );

  /**
   * Add tabs on profile archive page and user revision edit form
   */
  $items['user/%user_revision/revisions/%/edit/default'] = array(
    'title' => 'Archiv-Profil bearbeiten',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  );
  $items['user/%user_revision/revisions/%/edit/view'] = array(
    'title' => 'Archiv-Profil Ansicht',
    'type' => MENU_LOCAL_TASK,
    'weight' => -10,
    'load arguments' => array(3),
    'page callback' => 'pw_userarchives_goto_view_revision',
    'page arguments' => array(1),
    'access callback'=> 'pw_userarchives_user_revision_admin_access',
    'access arguments' => array(1),
    'file' => 'pw_userarchives.admin.inc',
  );
  $items['user/%user_revision/revisions/%/edit/all-revisions'] = array(
    'title' => 'Alle Profil-Versionen',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'load arguments' => array(3),
    'page callback' => 'pw_userarchives_all_revision_page_callback',
    'page arguments' => array(1),
    'access callback'=> 'pw_userarchives_user_revision_admin_access',
    'access arguments' => array(1),
    'file' => 'pw_userarchives.admin.inc',
  );

  $items['profile/%pw_profiles_username/archive/%/view'] = [
    'title' => 'Archiv-Profil Ansicht',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  ];

  $items['profile/%pw_profiles_username/archive/%pw_user_revision/edit'] = [
    'title' => 'Archiv-Profil bearbeiten',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'load arguments' => array(1),
    'page callback' => 'pw_userarchives_edit_revision_page_callback',
    'page arguments' => array(3),
    'access callback' => 'pw_userarchives_user_revision_admin_access',
    'access arguments' => array(3),
    'file' => 'pw_userarchives.admin.inc',
  ];

  $items['profile/%pw_profiles_username/archive/%pw_user_revision/all-revisions'] = [
    'title' => 'Alle Profil-Versionen',
    'type' => MENU_LOCAL_TASK,
    'weight' => 50,
    'load arguments' => array(1),
    'page callback' => 'pw_userarchives_all_revision_page_callback',
    'page arguments' => array(3),
    'access callback' => 'pw_userarchives_user_revision_admin_access',
    'access arguments' => array(3),
    'file' => 'pw_userarchives.admin.inc',
  ];

  $items['taxonomy/term/%taxonomy_term/reset-user-archive-cache'] = [
    'title' => 'User archive Einträge zurücksetzen/ neu aufbauen',
    'type' => MENU_CALLBACK,
    'page callback' => 'drupal_get_form',
    'page arguments' => ['pw_userarchives_reset_parliament_form', 2],
    'access arguments' => ['can reset user archive table'],
    'file' => 'pw_userarchives.admin.inc',
  ];

  return $items;
}



/**
 * Access callback.
 */
function pw_userarchives_user_revision_admin_access($account) {
  global $user;

  // Checks if user has permissions.
  $access = user_access('edit user revisions')
    || user_access('edit own user revisions')
    && $account->uid == $user->uid;

  // Checks if at least 2 revisions exist.
  $count = db_query("
    SELECT COUNT(*) AS expression
    FROM (
      SELECT 1 AS expression
      FROM user_revision ur
      WHERE (ur.uid = {$account->uid})
    ) subquery
  ")->fetchField();

  // Displays revisions tab only if both are true.
  return $access && ($count > 1);
}


/**
 * Implements hook_admin_paths().
 */
function pw_userarchives_admin_paths() {
  // Enables the edit from to use admin theme.
  if (variable_get('node_admin_theme')) {
    $paths = array(
      'user/*/revisions/*/edit' => TRUE,
    );
    return $paths;
  }
}



/**
 * Implements hook_permission().
 */
function pw_userarchives_permission() {

  // Adds permission items for editing revisions.
  return array(
    'edit user revisions' => array(
      'title' => t('Edit user revisions'),
      'restrict access' => TRUE,
    ),
    'edit own user revisions' => array(
      'title' => t('Edit own user revisions'),
      'description' => t('Allow users to edit their own user revisions'),
    ),
    'can reset user archive table' => array(
      'title' => t('Reset user archive table'),
      'description' => t('User can reset user archive table'),
    ),
  );
}



/**
 * Implements hook_entity_info_alter().
 */
function pw_userarchives_entity_info_alter(&$entity_info) {
  $entity_info['user']['controller class'] = 'UserArchiveController';
}

/**
 * Implements hook_user_insert().
 */
function pw_userarchives_user_insert(&$edit, $account, $category) {
  pw_userarchives_update_by_user($account);
  $account->user_archive_run = TRUE;
}

/**
 * Implements hook_user_update().
 */
function pw_userarchives_user_update(&$edit, $account, $category) {
  pw_userarchives_update_by_user($account);
  $account->user_archive_run = TRUE;
}


/**
 * Implements hook_user_delete().
 */
function pw_userarchives_user_delete($account) {
  db_delete('user_archive_cache')
    ->condition('uid', $account->uid)
    ->execute();
}


/**
 * Implements hook_user_revision_delete().
 *
 * Delete a user revision which may be stored in user archive table
 * when a user revision gets deleted.
 *
 * @param $revision
 */
function pw_userarchives_user_revision_delete($revision) {
  pw_userarchives_update_by_user($revision);
}


/**
 * Implements hook_pw_user_revision_edit().
 */
function pw_userarchives_pw_user_revision_edit($revision) {
  if (!isset( $revision->user_archive_run) || !$revision->user_archive_run) {
    pw_userarchives_update_by_user($revision);
  }
}

/**
 * Implements hook_node_insert().
 */
function pw_userarchives_node_insert($node) {
  if ($node->type == 'dialogue' && !empty($node->field_dialogue_recipient[LANGUAGE_NONE][0]['target_id'])) {
    pw_userarchives_update_by_user($node->field_dialogue_recipient[LANGUAGE_NONE][0]['target_id']);
  }
}

/**
 * Implements hook_node_update().
 */
function pw_userarchives_node_update($node) {
  if ($node->type == 'dialogue' && !empty($node->field_dialogue_recipient[LANGUAGE_NONE][0]['target_id'])) {
    pw_userarchives_update_by_user($node->field_dialogue_recipient[LANGUAGE_NONE][0]['target_id']);
  }
}

/**
 * Implements hook_node_delete().
 *
 * Beware that hook_node_delete is called before the node is deleted from the
 * database. Hence execution of pw_userarchives_cron needs to be deferred via
 * drupal_register_shutdown_function.
 */
function pw_userarchives_node_delete($node) {
  if ($node->type == 'dialogue' && !empty($node->field_dialogue_recipient[LANGUAGE_NONE][0]['target_id'])) {
    drupal_register_shutdown_function('pw_userarchives_update_by_user', $node->field_dialogue_recipient[LANGUAGE_NONE][0]['target_id']);
  }
}

/**
 * Implements hook_comment_insert().
 */
function pw_userarchives_comment_insert($comment) {
  if ($comment->node_type == 'comment_node_dialogue' && !empty($comment->uid)) {
    pw_userarchives_update_by_user($comment->uid);
  }
}

/**
 * Implements hook_comment_update().
 */
function pw_userarchives_comment_update($comment) {
  if ($comment->node_type == 'comment_node_dialogue' && !empty($comment->uid)) {
    pw_userarchives_update_by_user($comment->uid);
  }
}

/**
 * Implements hook_comment_delete().
 */
function pw_userarchives_comment_delete($comment) {
  if ($comment->node_type == 'comment_node_dialogue' && !empty($comment->uid)) {
    pw_userarchives_update_by_user($comment->uid);
  }
}


/**
 * Helper to rebuild user archive entries for a single politician
 *
 * @param bool|int|string|object $account
 * If false the currently logged in user will be used. If this is an integer
 * or a numeric string it is the user uid and the user account will be loaded.
 * If it is an object it need to be the Drupal user object. It should be
 * the user revision of the Politician.
 *
 * @param bool $reset_actual_profile
 */
function pw_userarchives_update_by_user($account = FALSE, $reset_actual_profile = TRUE) {
  try {
    $PWUser = new PWUser($account);
    if ($PWUser->isPolitician()) {
      $politician = new Politician($account);
      $userArchiveManager = new UserArchiveManager($politician);
      $userArchiveManager->updateEntries($reset_actual_profile);
    }
  }
  catch (\Exception $e) {
    $error_message = 'An error appeared while trying to rebuild user archive cache for user '. $account->uid .'/ '. $account->name .': '. $e->getMessage();
    watchdog_exception('pw_userarchives', $e, $error_message);
    drupal_set_message($error_message, 'error');
  }
}

/**
 * Batch callback for updating user archive entries for a user
 *
 * @param $uid
 * @param $context
 *
 * @throws \Exception
 */
function pw_userarchives_update_by_user_batch($uid, &$context) {
  $politician = Politician::loadFromUid($uid);
  $userArchiveManager = new UserArchiveManager($politician);
  $userArchiveManager->updateEntries(FALSE);

  $context['results'][] = $politician->getFullName() .' aktualisiert';
}


/**
 * batch finished callback for rebuild user archive entries for politicians
 * related to a parliament
 *
 * @param $success
 * @param $results
 * @param $operations
 */
function pw_userarchives_update_by_user_batch_finished($success, $results, $operations) {
  $counter = count($results);

  if ($success) {
    drupal_set_message('Die User Archive Einträge wurden für '. $counter .' Politiker erfolgreich aktualisiert');
  }
  else {
    drupal_set_message('Es ist ein Fehler aufgetreten', 'warning');
  }
}



/**
 * Helper to rebuild user archive entries for an updated parliament
 *
 * @todo use unique term tid instead of parliament name
 * @todo use queue for updating
 *
 * @param \Drupal\pw_globals\Parliament $parliament
 * The Parliament object of the updated parliament term
 *
 * @param string $original_name
 * The original term name. When a parliament name was changed this assures that
 * we can change the user archive entries connected to this parliament. Take
 *   this from
 * $term->original->name
 *
 * @param bool $reset_actual_profile
 */
function pw_userarchives_update_entries_by_parliament(Parliament $parliament, $original_name, $reset_actual_profile = FALSE) {
  $entriesFromDatabase = UserArchiveDatabase::getExistingArchiveEntries(['parliament_name' => $original_name]);

  if (!empty($entriesFromDatabase)) {
    foreach ($entriesFromDatabase as $entryFromDatabase) {
      $transaction = db_transaction();
      try {
        $userArchiveEntry = UserArchiveEntry::createFromDataBaseArray($entryFromDatabase);
        $politicianUserRevision = $userArchiveEntry->getPoliticianUserRevision();
        $userArchiveEntry->setParliamentName($parliament->getName());

        $question_form_is_open = (int) UserArchiveManager::checkIfQuestionFormOpen($politicianUserRevision);
        $question_form_is_open_change = UserArchiveManager::calcQuestionFormOpenChange($politicianUserRevision);
        if ($question_form_is_open_change !== NULL) {
          $timezone = 'UTC';
        }
        else {
          $timezone = '';
        }
        $userArchiveEntry->setQuestionFormOpenChange($question_form_is_open_change, $timezone);
        $userArchiveEntry->setQuestionFormOpen($question_form_is_open);
        $userArchiveEntry->save();
      }
      catch (\Exception $e) {
        $transaction->rollback();
        $error_message = 'An error appeared while trying to update user archive cache entry uid ' . $userArchiveEntry->getUid() . '/ vid ' . $userArchiveEntry->getVid() . ' for parliament ' . $parliament->getName() . ': ' . $e->getMessage();
        watchdog_exception('pw_userarchives', $e, $error_message);
        drupal_set_message($error_message, 'error');
      }
    }
  }
}


/**
 * Implements hook_cron().
 *  - at night we run through all user archive entries and check for entries
 *    which need a revalidation of question form open
 */
function pw_userarchives_cron() {

  if(date("H:i") != '01:00'){
    return;
  }

  $string_of_current_time = date('Y-m-d\TH:i:s', REQUEST_TIME);
  $currentDateTime = new \DateTime($string_of_current_time, new \DateTimeZone(date_default_timezone_get()));
  $currentDateTime->setTimezone(new \DateTimeZone('UTC'));
  $current_timestamp = $currentDateTime->getTimestamp();

  $query = db_select('user_archive_cache', 'uac')
    ->condition('question_form_open_change', $current_timestamp, '<')
    ->fields('uac')
    ->execute();

  while ($record = $query->fetchAssoc()) {
    $transaction = db_transaction();
    try {
      $userArchiveEntry = UserArchiveEntry::createFromDataBaseArray($record);
      $userArchiveEntry->updateQuestionFormSettings();
      $userArchiveEntry->save();
    }

    catch (\Exception $e) {
      $transaction->rollback();
      $error_message = 'An error appeared during cron when trying to revalidate question form open value.';
      if (is_array($record) && !empty($record)) {
        $error_message .= ' Array values: '. http_build_query($record) .'.';
      }
      $error_message .= ' Exception message: '. $e->getMessage();
      watchdog_exception('pw_userarchives', $e, $error_message);
    }
  }
}

/**
 * Implements hook_cron().
 *
 * Updates stats for users.
 *
 * 1. Fetch highest and actual vid of every grouped item.
 * 2. Modify query object and re-fetch data using the vids.
 * 3. Do the delete and update queries
 * 4. Update fields, index, etc.
 *
 * @deprecated
 */
function pw_userarchives_cron_ALT($uid = NULL, $reset_actual_profile = TRUE) {
  // $tracked_items_query -> hole das profile mit der höchsten vid je user/ parlament/ rolle aus der User Archive
  $tracked_items_query = db_select('user_archive_cache', 'uac');
  $tracked_items_query->addExpression('MAX(uac.vid)');
  $tracked_items_query->groupBy('uac.uid, uac.parliament_name, uac.user_role');

  $transaction = db_transaction();

  try {
    // check if election date or parliaments end date is reached, then delete profiles from meta table for triggering refresh
    if ($uid == NULL) {
      $tracked_items = [];
      $vocabulary = taxonomy_vocabulary_machine_name_load('parliaments');
      $parliaments = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));
      foreach ($parliaments as $parliament) {
        if (pw_userarchives_check_refresh_profiles($parliament)) {
          $tracked_items = array_merge($tracked_items, $tracked_items_query
            ->condition('parliament_name', $parliament->name)
            ->execute()
            ->fetchCol());
          db_delete('user_archive_cache')
            ->condition('parliament_name', $parliament->name)
            ->execute();
        }
      }
    } else {
      $tracked_items = $tracked_items_query
        ->condition('uid', $uid)
        ->execute()
        ->fetchCol();
      // empty cache if uid is specified
      db_delete('user_archive_cache')
        ->condition('uid', $uid)
        ->execute();
    }

    // db_select: user revision
    $query = db_select('user_revision', 'ur');
    $query->addExpression('MAX(ur.vid)', 'vid');

    // join taxonomy terms for parliament names
    $query->join('field_revision_field_user_parliament', 'u_parl', "u_parl.entity_type = 'user' AND ur.vid = u_parl.revision_id");
    $query->join('taxonomy_term_data', 'parliament', 'parliament.tid = u_parl.field_user_parliament_tid');

    // join fractions for fraction tids
    $query->leftJoin('field_revision_field_user_fraction', 'fraction_tid', "fraction_tid.entity_type = 'user' AND fraction_tid.revision_id = ur.vid");
    $query->leftJoin('taxonomy_term_data', 'fraction', 'fraction.tid = fraction_tid.field_user_fraction_tid');

    // join revisionable roles for user_roles
    $query->join('field_revision_field_user_roles_for_view_mode_s', 'role_tid', "role_tid.entity_type = 'user' AND role_tid.revision_id = ur.vid");
    $query->join('taxonomy_term_data', 'role', 'role.tid = role_tid.field_user_roles_for_view_mode_s_tid');

    // query conditions
    $query->condition('ur.status', '1');
    if ($uid != NULL) {
      $query->condition('ur.uid', $uid);
    }
    $query->condition('role.name', array('Deputy', 'Candidate'));
    $query->groupBy('ur.uid, u_parl.field_user_parliament_tid, role_tid.field_user_roles_for_view_mode_s_tid, fraction_tid.field_user_fraction_tid');

    // fetch all relevant vids as flat array
    $vids = $query->execute()->fetchCol();

    if (empty($vids)) {
      return;
    }

    /*
     * second step: modify query and get items by its vids
     */

    // set vids as condition
    $query->condition('ur.vid', $vids);

    // unset group and max(vid) expression
    array_pop($query->getGroupBy());
    array_pop($query->getExpressions());

    // readd vid as regular field
    $query->addField('ur', 'vid', 'vid');

    // add all the other fields (and joins)
    $query->addField('ur', 'uid'); // NOTE: keep as index 1 for fetchCol
    $query->addField('ur', 'name', 'user_name');
    $query->addField('parliament', 'name', 'parliament_name');
    $query->addField('fraction', 'name', 'fraction_name');
    $query->addExpression('LOWER(role.name)', 'user_role');

    // join parliament election to get timestamp for elections
    $query->leftJoin('field_revision_field_parliament_election', 'pe', "pe.entity_type='taxonomy_term' AND pe.entity_id = u_parl.field_user_parliament_tid");
    $query->addExpression('UNIX_TIMESTAMP(pe.field_parliament_election_value)', 'timestamp');

    // join parliament valid AND question form closed to check if the profile is open for questions or not
    $query->leftJoin('field_revision_field_parliament_valid', 'pv', "pv.entity_type='taxonomy_term' AND pv.entity_id = u_parl.field_user_parliament_tid AND pv.field_parliament_valid_value < NOW() AND (pv.field_parliament_valid_value2 IS NULL OR pv.field_parliament_valid_value2 > NOW())");
    $query->leftJoin('field_revision_field_user_question_form_closed', 'qf_closed', "qf_closed.entity_type='user' AND qf_closed.revision_id = ur.vid");

    // CHECK if question form is open
    $query->addExpression("
      COUNT(pv.field_parliament_valid_value) > 0 AND
      (user_joined.field_user_joined_value IS NULL OR user_joined.field_user_joined_value < NOW()) AND
      (user_retired.field_user_retired_value IS NULL OR user_retired.field_user_retired_value > NOW()) AND
      (role.name = 'deputy' AND pe.field_parliament_election_value < NOW() OR role.name = 'candidate' AND pe.field_parliament_election_value > NOW()) AND
      qf_closed.field_user_question_form_closed_value IS NULL", 'question_form_open');

    // join joined to get valid from
    $query->leftJoin('field_revision_field_user_joined', 'user_joined', "user_joined.entity_type = 'user' AND user_joined.revision_id = ur.vid");
    $query->addField('user_joined', 'field_user_joined_value', 'user_joined');

    // join retired to get valid until
    $query->leftJoin('field_revision_field_user_retired', 'user_retired', "user_retired.entity_type = 'user' AND user_retired.revision_id = ur.vid");
    $query->addField('user_retired', 'field_user_retired_value', 'user_retired');

    // join dialogues fields to get number of questions
    $query->leftJoin("field_data_field_dialogue_recipient", "dia_rp", "dia_rp.entity_type = 'node' AND dia_rp.field_dialogue_recipient_target_id = ur.uid");
    $query->leftJoin("field_data_field_parliament", "dia_parl", "dia_parl.entity_type = 'node' AND dia_parl.entity_id = dia_rp.entity_id AND dia_parl.field_parliament_tid = parliament.tid");
    $query->leftJoin("field_data_field_dialogue_before_election", "dia_election", "dia_election.entity_type = 'node' AND dia_election.entity_id = dia_parl.entity_id AND
          CASE
          WHEN role.name = 'Candidate' THEN dia_election.field_dialogue_before_election_value = 1
          ELSE dia_election.field_dialogue_before_election_value = 0
          END");
    $query->leftJoin("node", "n", "dia_rp.entity_id = n.nid AND n.status = 1");
    $query->addExpression("IFNULL(COUNT(DISTINCT CASE WHEN n.status = 1 THEN dia_election.entity_id END), 0)", "number_of_questions");

    // join comments to dialogues to get number of answers without standard replies
    $query->leftJoin("comment", "c", "dia_election.entity_id = c.nid AND c.status = 1");
    $query->leftJoin("field_data_field_dialogue_is_standard_reply", "standard_reply", "standard_reply.entity_type = 'comment' AND standard_reply.entity_id = c.cid");
    $query->addExpression("IFNULL(COUNT(DISTINCT CASE WHEN n.status = 1 AND c.status = 1 THEN c.nid END), 0) - IFNULL(SUM(CASE WHEN n.status = 1 AND c.status = 1 THEN standard_reply.field_dialogue_is_standard_reply_value END), 0)", "number_of_answers");

    // get number of standard replies
    $query->addExpression("IFNULL(SUM(standard_reply.field_dialogue_is_standard_reply_value), 0)", "number_of_standard_replies");

    // join users to get actual profile
    $query->leftJoin("users", "u", "ur.vid = u.vid");
    $query->groupBy('ur.vid');
    $query->addExpression("NOT ISNULL(u.vid)", "actual_profile");

    // join user archive cache for comparing
    $query->leftJoin('user_archive_cache', 'uac', "ur.vid = uac.vid");

    // need fields for comparison in having clause
    $query->addField("uac", "number_of_questions", "uac_number_of_questions");
    $query->addField("uac", "number_of_answers", "uac_number_of_answers");
    $query->addField("uac", "number_of_standard_replies", "uac_number_of_standard_replies");

    $query->having('(ISNULL(uac.number_of_questions)
          OR uac_number_of_questions != number_of_questions
          OR uac_number_of_answers != number_of_answers
          OR uac_number_of_standard_replies != number_of_standard_replies)');

    // nothing to update
    if (empty($query) || $query->execute()->rowCount() == 0) {
      return;
    }

    // fetch vids and uids
    $result = $query->execute()->fetchAllAssoc('vid', PDO::FETCH_ASSOC);
    $uids = array_unique(array_column($result, 'uid'));

    // delete and insert archive cache
    $fields = array_merge(array_keys($query->getFields()), array_keys($query->getExpressions()));
    unset($fields[array_search('uac_number_of_questions', $fields)]);
    unset($fields[array_search('uac_number_of_answers', $fields)]);
    unset($fields[array_search('uac_number_of_standard_replies', $fields)]);
    sort($fields);

    foreach ($result as $row) {
      db_delete('user_archive_cache')
        ->condition('parliament_name', $row['parliament_name'])
        ->condition('user_role', $row['user_role'])
        ->condition('uid', $row['uid'])
        ->condition('fraction_name', $row['fraction_name'])
        ->execute();

      unset($row['uac_number_of_questions']);
      unset($row['uac_number_of_answers']);
      unset($row['uac_number_of_standard_replies']);
      ksort($row);

      db_insert('user_archive_cache')
        ->fields($fields)
        ->values($row)
        ->execute();
    }

    // set actual / newest profile
    if ($reset_actual_profile) {
      foreach ($uids as $uid) {
        // restore to newest profile, especially after importing older profiles
        pw_reset_actuale_profile($uid);
      }
    }

    // delete file entries with fid=0 because it will break field_attach_update
    db_delete('file_usage')
      ->condition('fid', 0)
      ->condition('type', 'user')
      ->condition('id', $uids)
      ->execute();
    db_delete('field_data_field_user_image_gallery')
      ->condition('field_user_image_gallery_fid', 0)
      ->condition('entity_type', 'user')
      ->condition('entity_id', $uids)
      ->execute();
    db_delete('field_revision_field_user_image_gallery')
      ->condition('field_user_image_gallery_fid', 0)
      ->condition('entity_type', 'user')
      ->condition('entity_id', $uids)
      ->execute();

    $politician_index = search_api_index_load('politician_archive_index');
    $items_to_track_after_update = $tracked_items_query
      ->condition('uac.vid', $vids)
      ->execute()
      ->fetchCol();

    if ($politician_index) {
      try {
        search_api_track_item_insert('user_revision', array_diff($items_to_track_after_update, $tracked_items));
      }
      catch (PDOException $e) {
        // Due to the recursive call earlier the $tracked_items might be
        // outdated resulting in duplicate INSERT statements for the same key.
        watchdog_exception('pw_userarchives', $e);
      }
      search_api_track_item_change('user_revision', array_intersect($tracked_items, $items_to_track_after_update));
      search_api_track_item_delete('user_revision', array_diff($tracked_items, $items_to_track_after_update));
    }

    // finally check for outdated revisions which can be deleted
   // pw_delete_old_user_revisions($uid);
  }
  catch (Exception $e) {
    $transaction->rollback();
    throw $e;
  }
}

/**
 * Implements hook_search_api_item_type_info().
 */
function pw_userarchives_search_api_item_type_info() {
  $types['user_revision'] = [
    'name' => t('User archive entries'),
    'datasource controller' => 'UserArchiveDataSourceController',
    'entity_type' => 'user',
  ];
  return $types;
}

/**
 * Implements hook_search_api_alter_callback_info().
 */
function pw_userarchives_search_api_alter_callback_info() {
  $callbacks['user_archive_alter'] = [
    'name' => t('User archive fields'),
    'description' => t('Adds user archive fields to the items.'),
    'class' => 'UserArchiveAlterAddFields',
    'weight' => 100,
  ];
  return $callbacks;
}

/**
 * Returns last revision ID matching $uid, $parliament and $role.
 *
 * @param $uid
 *   The user ID.
 * @param $parliament
 *   The parliament term.
 * @param $role
 *   The politician role: candidate od deputy.
 *
 * @return int
 *   The last revision ID matching the provided criteria.
 */
function pw_userarchives_find_revision($uid, $parliament, $role) {
  $q = db_select('user_archive_cache', 'uac')
    ->fields('uac', ['vid'])
    ->condition('uac.uid', $uid)
    ->condition('uac.parliament_name', $parliament->name)
    ->condition('uac.user_role', $role)
    ->orderBy('uac.vid', 'DESC');
  return $q->execute()->fetchField();
}

/**
 * Returns requested versions of user objects with all fields attached.
 *
 * @param  $vids
 *   The revision IDs.
 *
 * @return array
 *   The fully loaded user objects having the given revision IDs.
 */
function pw_userarchives_politician_load_multiple($vids) {
  if (empty($vids)) {
    return [];
  }

  $q = db_select('user_revision', 'ur');
  $q->join('users', 'u', 'u.uid = ur.uid');
  $q->leftJoin('user_archive_cache', 'uac', 'ur.vid = uac.vid');
  $q->fields('ur')
    ->fields('u', ['created', 'uuid'])
    ->fields('uac', ['actual_profile', 'number_of_questions', 'number_of_answers', 'user_role'])
    ->condition('ur.vid', $vids);
  $q->addField('ur', 'timestamp', 'revision_timestamp');
  $q->addField('ur', 'authorid', 'revision_uid');

  $sorted_users = array_flip($vids);

  foreach($q->execute()->fetchAllAssoc('uid') as $uid => $properties) {
    $users[$uid] = $properties;
    $users[$uid]->data = unserialize($properties->data);
    $users[$uid]->roles[DRUPAL_AUTHENTICATED_RID] = 'authenticated user';
    $users[$uid]->roles[PW_GLOBALS_POLITICIAN_RID] = 'Politician';
    if ($properties->user_role == 'candidate') {
      $users[$uid]->roles[PW_GLOBALS_CANDIDATE_RID] = 'Candidate';
    }
    elseif ($properties->user_role == 'deputy') {
      $users[$uid]->roles[PW_GLOBALS_DEPUTY_RID] = 'Deputy';
    }
    unset($users[$uid]->user_role);

    $sorted_users[$properties->vid] = $users[$uid];
  }

  field_attach_load_revision('user', $users);

  return array_filter($sorted_users, 'is_object');
}

/**
 * check if profiles needs to be refreshed based on parliament valid dates and
 * election date.
 */
function pw_userarchives_check_refresh_profiles($parliament) {

  $do_refresh_profiles = FALSE;
  $timespan_close_before_election = 6 * 3600;

  // first check if election date was reached
  $field_parliament_election = field_get_items('taxonomy_term', $parliament, 'field_parliament_election');
  if ($field_parliament_election) {
    $time_diff = time() - (strtotime($field_parliament_election[0]['value']) - $timespan_close_before_election);
    $do_refresh_profiles = $time_diff <= 6000 && $time_diff > 0;
  }
  if (!$do_refresh_profiles) {

    // secondly check if valid end dates were reached
    $field_parliament_valid = field_get_items('taxonomy_term', $parliament, 'field_parliament_valid');
    if ($field_parliament_valid) {
      foreach ($field_parliament_valid as $valid_date) {
        if (!empty($valid_date['value2'])) {
          $time_diff = time() - strtotime($valid_date['value2']);
          $do_refresh_profiles = $time_diff <= 6000 && $time_diff > 0;
          if ($do_refresh_profiles) {
            break;
          }
        }
      }
    }
  }
  return $do_refresh_profiles;
}

/**
 * Deletes old user revisions from database.
 *
 *  * @param int $uid
 *   The user id.
 *
 * @return bool
 *   False if uid is zero or not a numeric value.
 */
function pw_delete_old_user_revisions($uid) {

  if (!is_numeric($uid) || $uid == 0) {
    return FALSE;
  }

  $days_buffer = 30;
  $time_buffer = time() - (86400 * $days_buffer);

  // query for all revision which are older than X days and which are not in the user_archive_cache table
  $query = db_select('user_revision', 'ur');
  $query->addField('ur', 'uid');
  $query->addField('ur', 'vid');
  $query->addField('uac', 'id');
  $query->join('field_revision_field_user_roles_for_view_mode_s', 'ro', 'ro.entity_id=ur.uid AND ro.revision_id=ur.vid');
  $query->join('taxonomy_term_data', 'rn', 'rn.tid=ro.field_user_roles_for_view_mode_s_tid');
  $query->leftJoin('user_archive_cache', 'uac', 'ur.uid = uac.uid AND ur.vid = uac.vid');
  $query->join('users', 'u', 'ur.uid = u.uid AND ur.vid != u.vid');
  $query->condition('ur.uid', $uid);
  $query->condition('ur.timestamp', $time_buffer, '<');
  $query->condition('rn.name', 'Politician');
  $query->isNull('id');
  $result = $query->execute();
  $number_of_revisions = $result->rowCount();

  // revisions found
  if ($number_of_revisions > 0) {

    // delete all those revisions
    while ($revision = $result->fetchObject()) {
      user_revision_delete($revision);
    }

    // leave a message
    watchdog('pw_userarchives', ':number_of_revisions user revisions deleted which were older than :days_buffer days and were not associated with user_archive_cache', array(
      ':number_of_revisions' => $number_of_revisions,
      ':days_buffer' => $days_buffer,
    ));
  }

  return TRUE;
}

/**
 * Chaecks and resets user revision to actual (newest) profile
 * @param $uid
 */
function pw_reset_actuale_profile($uid, $exclude_vids=array()) {

  // load current profile
  $user = user_load($uid, TRUE);

  if (!$user) {
    return;
  }

  // load newest profile which is open for questions
  $query = db_select('user_archive_cache', 'uac');
  $query->addField('uac', 'vid');
  $query->condition('uac.uid', $uid);
  if(!empty($exclude_vids)){
    $query->condition('uac.vid', $exclude_vids, 'NOT IN');
  }
  $query->orderBy('uac.question_form_open', 'DESC');
  $query->orderBy('uac.timestamp', 'DESC');
  $query->orderBy('uac.user_role=\'deputy\'', 'DESC');
  $query->orderBy('uac.vid', 'DESC');
  $result = $query->execute()->fetchAssoc();
  $newest_vid = $result['vid'];

  // check if current vid is newest
  if ($user->vid != $newest_vid) {

    // load full revision
    $user_revision = user_revision_load($uid, $newest_vid);

    // retrieve roles and add them to user object
    $role_tids = _pw_array_flatten($user_revision->field_user_roles_for_view_mode_s, FALSE);
    $roles_terms = taxonomy_term_load_multiple($role_tids);
    $user_revision->roles = [];
    foreach ($roles_terms as $role_term) {
      $role = user_role_load_by_name($role_term->name);
      $user_revision->roles[$role->rid] = $role->name;
    }
    $user_revision->revision = 1;

    // add custom abort flag to prevent from circular updates
    $user_revision->abort_update = 1;
    $user_revision->log = t('Copy of the revision from %date.', array('%date' => format_date($user_revision->revision_timestamp)));
    user_save($user_revision, (array) $user_revision);
    watchdog('user', 'reverted %title revision %revision.', array('%title' => $user_revision->name, '%revision' => $user_revision->vid));

    // recorrect user archive cache
    db_delete('user_archive_cache')
      ->condition('uid', $uid)
      ->execute();
    pw_userarchives_update_by_user($uid, FALSE);
  }
}


/**
 * Implements hook_views_api().
 */
function pw_userarchives_views_api() {
  return array(
    'api' => '3',
    'path' => drupal_get_path('module', 'pw_userarchives') . '/views',
  );
}


/**
 * Save an edited user revision. Mostly taken form User Revision Edit module
 * ((@see _user_revision_edit_save() there)
 *
 * @param $revision
 * @param $edits
 */
function _pw_userarchives_user_revision_edit_save(&$revision, $edits) {
  global $user;

  // Updates revision object.
  $revision->authorid = $user->uid;
  $revision->timestamp = REQUEST_TIME;

  $picture = NULL;
  if (isset($edits['picture_delete']) && $edits['picture_delete'] == 1) {
    // Deletes picture from disk.
    file_delete($revision->picture);
    $revision->picture = 0;
  }
  elseif (isset($edits['picture_upload'])
    && is_object($edits['picture_upload'])) {
    $picture = $edits['picture_upload'];
    $revision->picture = $picture->fid;
  }
  elseif (isset($revision->picture) && is_object($revision->picture)) {
    $revision->picture = $revision->picture->fid;
  }

  // Updates the database record.
  drupal_write_record('user_revision', $revision, 'vid');

  // Uploads the picture.
  if (is_object($picture)) {
    file_usage_add($picture, 'user_revision', 'user', $revision->vid);
    $revision->picture = $picture;
  }

  // Updates the FAPI fields for the selected revision and restores the user.
  $account = user_load($revision->uid);
  field_attach_update('user', $revision);
  if ($account->vid != $revision->vid) {
    field_attach_update('user', $account);
  }
  entity_get_controller('user')->resetCache(array($revision->uid));

  // Implement a hook to be able to react on user revision update
  module_invoke_all('pw_user_revision_edit', $revision);

}


/**
 * Define the possible politician roles related to a parliament
 */
function pw_userarchives_politician_roles() {
  return [
    'deputy' => 'Mandat',
    'candidate' => 'Kandidatur',
  ];
}